# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a50ee98b6181a931c15969b97daa4cb8ce0a12f3b0bed567c9678153a6bf1119fb59b942bffc7948689943372f267ddbf856c7ef20d4cc976273662c90b92a27
# Use different runs of `rake secret` for development and test
test:
  secret_key_base: 4b532302bd24127595c04f7a36ba791f2aa519c1e82c03abf913b99b043338c4191efd8ca645e8ca536e1a31f62d42464c4e19c674723fde2dbf3955f87e83d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
